#!/usr/bin/env bash

if [ -n "$DUALVIEW_SHELL" ]; then
    exec "$ORIGINAL_SHELL" "$@"
fi

export DUALVIEW_SHELL=1

if [ "$(uname -s)" = "Darwin" ]; then
    exec "$ORIGINAL_SHELL" "$@"
fi

exec unshare -nc -- "$ORIGINAL_SHELL" "$@"
